### ISSUE TITLE
请求获得关于该项目日语注音的帮助

### ISSUE THREAD

**Issue by ymd45921** [ErogeHelper/ErogeHelper#19]
您好！

我正在尝试在本地为日文汉字进行注音，遇到了困难；我想到 ErogeHelper 似乎是通过加载一个庞大的字典文件实现了离线对于日文语句分词并为汉字注音的功能，所以希望可以获得帮助。

我参考了一些具有可以为日文汉字注音的开源项目，它们大多都使用 Yahoo 等服务商提供的 API 在线转换，而不能实现离线转换；而 Kakasi 似乎并没有适用于 Windows 的 build…… 于是遇到了困境，希望可以得到您的帮助。

**Comment by ZUIcat** [comment]
现在这几个Gal翻译器基本用的都是MeCab，一个日语分词系统。

**Comment by luojunyuan** [comment]
win10以上的系统你可以直接用winrt里的形态素解析(build10240)，不需要其他依赖
https://learn.microsoft.com/ja-jp/uwp/api/windows.globalization.japanesephoneticanalyzer?view=winrt-22621
https://github.com/ErogeHelper/ErogeHelper/blob/dev/ErogeHelper/Platform/WinRTHelper/JapaneseAnalyzerWinRT.cs#L23

MeCab会更强大。有什么疑问或者不明的点欢迎给我发邮件。

**Comment by ymd45921** [comment]
好的，我去研究一下，谢谢
